---
title: "Nanopore iBAT, correlation by flowcell"
author: "Christoph Kiefer"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output:
    html_document:
        toc: true
        toc_float: true
        toc_depth: 2
        fig_caption: false
        dev: "svg"
editor_options:
    chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
    echo = FALSE,
    message = FALSE,
    warning = FALSE,
    cache = FALSE,
    fig.width = 6.85 / 2,
    fig.asp = 0.65,
    out.width = 800)
```

```{r loadPackages}
source(".Rprofile")
suppressPackageStartupMessages({
    library("dplyr")
    library("readr")
    library("purrr")
    library("ggplot2")
    library("ggthemes")
    library("ggpmisc")
    library("scales")
    library("ggpubr")
    library("scattermore")
    library("GGally")
})

rename <- dplyr::rename
select <- dplyr::select
```


# Setup

This is done on unnormalised data. Neither the counts nor the tpm are normalised!


# Sample wise comparison

```{r importData2}
df <- read_tsv(snakemake@input[[1]], col_types = "cccci")
```

## Teloprime

```{r}
df %>% 
    filter(library == "teloprime") %>%
    tidyr::pivot_wider(names_from = flowcell, values_from = NumReads) %>% 
    mutate_if(is.numeric, tidyr::replace_na, 0) %>% 
    filter(rowSums(dplyr::select(., flowcell1, flowcell2)) > 0) %>% 
    ggplot(aes(flowcell1, flowcell2)) +
    geom_scattermore(
        pointsize = 6,
        alpha = .5,
        pixels = c(1024, 1024 * .65)) +    
    facet_wrap(~barcode) +
    geom_abline(slope = 1, lty = 2, lwd = .25) +
    stat_poly_eq(formula = y ~ x,
        aes(label = paste(..rr.label.., sep = "~~~")),
        parse = TRUE, family = "Helvetica", size = 2, colour = "grey30",
        label.x.npc = "left", label.y.npc = "top") +
    scale_x_continuous(
        breaks = 10^seq(0:5),
        labels = trans_format("log10", math_format(10^.x)),
        trans = "log1p") +
    scale_y_continuous(
        breaks = 10^seq(0:5),
        labels = trans_format("log10", math_format(10^.x)),
        trans = "log1p") +
    theme_tufte(base_size = 8, base_family = "Helvetica") +
    geom_rangeframe(sides = 'bl', na.rm = FALSE) +
    theme(legend.key.size = unit(.33, "cm"))
```

## cDNA

```{r}
df %>%
    filter(library == "cdna") %>%
    tidyr::pivot_wider(names_from = flowcell, values_from = NumReads) %>%
    mutate_if(is.numeric, tidyr::replace_na, 0) %>%
    filter(rowSums(dplyr::select(., flowcell1, flowcell2)) > 0) %>%
    ggplot(aes(flowcell1, flowcell2)) +
    geom_scattermore(
        pointsize = 6,
        alpha = .5,
        pixels = c(1024, 1024 * .65)) +       facet_wrap(~barcode) +
    geom_abline(slope = 1, lty = 2, lwd = .25) +
    stat_poly_eq(formula = y ~ x,
        aes(label = paste(..rr.label.., sep = "~~~")),
        parse = TRUE, family = "Helvetica", size = 2, colour = "grey30",
        label.x.npc = "left", label.y.npc = "top") +
    scale_x_continuous(
        breaks = 10^seq(0:5),
        labels = trans_format("log10", math_format(10^.x)),
        trans = "log1p") +
    scale_y_continuous(
        breaks = 10^seq(0:5),
        labels = trans_format("log10", math_format(10^.x)),
        trans = "log1p") +
    theme_tufte(base_size = 8, base_family = "Helvetica") +
    geom_rangeframe(sides = 'bl', na.rm = FALSE) +
    theme(legend.key.size = unit(.33, "cm"))
```
