# GENCODE version
GENCODE_VERSION: "M22"

# Paths to software
BEDTOOLS: "/data/bin/bedtools/bedtools-v2.28/bedtools"
MASHMAP: "/data/home/christophak/bin/mashmap"
STRINGTIE: "/data/home/christophak/src/stringtie-2.1.4.Linux_x86_64/stringtie"
FLAIR: "/data/home/christophak/src/flair-1.5/"
