# GENCODE version
GENCODE_VERSION: "M22"

# Sample info
SAMPLE_INFO: "conf/sampleInfo.csv"

# Paths to software
BEDTOOLS: "/data/bin/bedtools/bedtools-v2.28/bedtools"
MASHMAP: "/data/home/christophak/bin/mashmap"
STRINGTIE: "/data/home/christophak/src/stringtie-2.2.0.Linux_x86_64/stringtie"
FLAIR: "/data/home/christophak/src/flair-1.5/"

# Reannotation parameters
SJ_cutoff: 10 # splice junction cutoff for both flair and stringtie
SUPPORT_cutoff: 3 # required mappings  for flair to keep a transcript
